
import java.awt.Toolkit;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author TEST
 */
public class DietPlan extends javax.swing.JFrame {

//FOR CLEARING THE INPUTS FIELD
private void clearfield() {
    name.setText(null);
    age.setText(null);
    height.setText(null);
    weight.setText(null);
    choice.setText(null);
    gender.setText(null);
}

/**
 * ***********THIS IS THE DIET MANAGEMENT CODE***************
 */
//to calculate BMI
static String BMIcalculator(double Height, double Weight) {
    double BMIValue = Weight / (Height * Height) * 10000;
    String BMIFinal = String.format("%.2f", BMIValue);
    return BMIFinal;

}

/* ***********THIS IS THE DIET MANAGEMENT CODE****************/
public static double ActiveLevelCounter(int Activity) {

    //Here we are finding the physical intensity level of the user
    //Counter for the multiplication in the calorie section
    //if we enter the number other than 1-5 it counts the counter value as 1
    double Counter = 1;

    if (Activity == 1) {
        //Activity level is sedentary
        Counter = 1.2;
    } else if (Activity == 2) {
        //Activity level is lightly active
        Counter = 1.375;
    } else if (Activity == 3) {
        //Activity level is moderately active
        Counter = 1.55;
    } else if (Activity == 4) {
        //Activity level is  active
        Counter = 1.725;
    } else if (Activity == 5) {
        //Activity level is very active
        Counter = 1.9;
    }
    return Counter;
}

/**
 * **********THIS IS THE DIET MANAGEMENT CODE***************
 */
static int Calories(String Gender, int Age, double Height, double Weight, double ActiveLevel) {

//to calulate calories
    if (Gender.equals("male")) {
        return (int) ((10 * Weight + 6.25 * Height - (5 * Age) + 5) * ActiveLevel);

    } else if (Gender.equals("female")) {
        return (int) ((10 * Weight + 6.25 * Height - (5 * Age) - 161) * ActiveLevel);

    } else {
        System.out.println("Invalid gender input !");
        return -1;
    }

}

/**
 * Creates new form diet_man
 */
public DietPlan() {
    initComponents();
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/icon_256x256.jpg"))); //FOR ICON 
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        activity = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        check = new javax.swing.JButton();
        back = new javax.swing.JButton();
        gender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        choice = new javax.swing.JTextField();
        exit = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diet Plan Management ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        jLabel1.setText("WELCOME");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Age");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter Gender");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter Height (cm)");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter Weight (kg)");

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        weight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Select Your Physical Activity Level In A Scale Of 1-5 Mentioned Below ");

        height.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        height.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        check.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        check.setText("Check Diet Plan");
        check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("1.  Sedentary");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("2.  Lightly active");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("3.  Moderately active");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("4.  Active");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("5.  Very active");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Enter Your Choice");

        choice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        choice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        exit.setText("Exit");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(check)))
                        .addGap(26, 26, 26)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weight)
                                    .addComponent(height)
                                    .addComponent(age)
                                    .addComponent(gender)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(name)))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(choice, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(gender)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(height))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    BACK BUTTON
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int id=Login.getUser_id();
        Dashboard dash = new Dashboard();
        dash.getDetails(id);
        dash.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backActionPerformed

//    CHECK DIET PLAN BUTTON CODE
    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:

        /**
         * *********THIS IS THE DIET MANAGEMENT CODE***************
         */
        
       
        String activity = choice.getText();
        int Activity = Integer.parseInt(activity);

        String Name = name.getText();

        String Age = age.getText();
        int year = Integer.parseInt(Age);

//        int Activity = activity.hashCode();
        String Gender = gender.getText();

        String Weight = weight.getText();
//         if((Name && year && Gender && ht  && wt  &&  Activity)){
//            
//        }
//        else{
//            
//        }
        double wt = Double.parseDouble(Weight);

        String Height = height.getText();
        double ht = Double.parseDouble(Height);

        //to calc active level
        double ActiveLevel = ActiveLevelCounter(Activity);

        //BMI value to find the weight level /  body condition
        double BMI = Double.parseDouble(BMIcalculator(ht, wt));

        //here we store calories count for the Macros ratio ,weight maintain, weight gain or weight loss
        int CalorieCount = Calories(Gender, year, ht, wt, ActiveLevel);

        //Final Diet Plan
        DietPlanner(Name, CalorieCount, BMI);

        clearfield();
    }//GEN-LAST:event_checkActionPerformed

    private void choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_choiceActionPerformed

//    EXIT BUTTON CODE
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

/**
 * *****************THIS IS THE DIET MANAGEMENT CODE***************
 */
static void DietPlanner(String Name, int CalorieCount, double BMI) {
    //now we are calculating ratio / percentage for macros
    //for carbohydrates
    //Here we are dividing by 4 because 1 gm of carbs gives 4 calories
    double MinCarbs = ((CalorieCount * 0.55) / 4);
    String Carbs55 = String.format("%.2f", MinCarbs);
    double MaxCarbs = ((CalorieCount * 0.60) / 4);
    String Carbs60 = String.format("%.2f", MaxCarbs);

    //for protein
    //Here we are dividing by 4 because 1 gm of protein gives 4 calories
    double MinProtein = ((CalorieCount * 0.25) / 4);
    String Protein25 = String.format("%.2f", MinProtein);
    double MaxProtein = ((CalorieCount * 0.30) / 4);
    String Protein30 = String.format("%.2f", MaxProtein);

    //for fats
    //Here we are dividing by 9 because 1 gm of fat gives 9 calories
    double MinFats = ((CalorieCount * 0.15) / 9);
    String Fats15 = String.format("%.2f", MinFats);
    double MaxFats = ((CalorieCount * 0.20) / 9);
    String Fats20 = String.format("%.2f", MaxFats);

    //Here I am declaring the calories. so ,I can easily add their variable names in the print statement line
    //calories for weight loss
    int MildWeightLossCalories = CalorieCount - 250;
    int WeightLossCalories = CalorieCount - 500;
    int ExtremeWeightLossCalories = CalorieCount - 1000;

    //calories for weight gain
    int MildWeightGainCalories = CalorieCount + 250;
    int WeightGainCalories = CalorieCount + 500;
    int FastWeightGainCalories = CalorieCount + 1000;

    JOptionPane.showMessageDialog(null, "Hi " + Name + ". Here Is Your Diet Planner\nYour Daily Required Calories " + CalorieCount + "\nYour Daily Diet Plan\nRequired Calorie To Maintain Present Weight : " + CalorieCount + "Calories Per Day\nCarbohydrates (Grams) portion in your diet : " + Carbs55 + " - " + Carbs60 + "Grams\nProtein (Grams) portion in your diet : " + Protein25 + " - " + Protein30 + "Grams\nFats (Grams) portion in your diet : " + Fats15 + " - " + Fats20 + "Grams\nNormal Weight BMI Range 18.5 - 24.9\nYour BMI Value : " + BMI + ".");

    if (BMI < 18.5) {
        JOptionPane.showMessageDialog(null, "You Are Under Weight.\nYou Need To Gain Weight\nWe recommend below plans for you\nRequired Calorie To Mild Weight Gain (0.25Kg/Week) : " + MildWeightGainCalories + " Calories Per Day\nRequired Calorie To Weight Gain (0.5Kg/Week) : " + WeightGainCalories + " Calories Per Day\nRequired Calorie To Fast Weight Gain (1Kg/Week) : " + FastWeightGainCalories + " Calories Per Day");
    } else if (BMI >= 18.5 && BMI < 25) {
        JOptionPane.showMessageDialog(null, "You Are Normal Weight.\nYou are maintaining healthy weight , Keep going.\nWe recommend below plans for you\nRequired Calorie To Mild Weight Gain (0.25Kg/Week) : " + MildWeightGainCalories + " Calories Per Day.\nRequired Calorie To Weight Gain (0.5Kg/Week) : " + WeightGainCalories + " Calories Per Day.\nRequired Calorie To Fast Weight Gain (1Kg/Week) : " + FastWeightGainCalories + " Calories Per Day.");
    } else if (BMI >= 25 && BMI < 30) {
        JOptionPane.showMessageDialog(null, "You Are Over Weight.\nYou Need To Loose Weight .\nWe recommend below plans for you\nRequired Calorie To Mild Weight Loss (0.25Kg/Week) : " + MildWeightLossCalories + " Calories Per Day\nRequired Calorie To Weight Loss (0.5Kg/Week) : " + WeightLossCalories + " Calories Per Day\nRequired Calorie To Extreme Weight Loss (1Kg/Week) : " + ExtremeWeightLossCalories + " Calories Per Day");
    } else {
        JOptionPane.showMessageDialog(null, "You Are Obese.\nYou Need To Loose Huge Weight \nWe recommend below plans for you.\nRequired Calorie To Mild Weight Loss (0.25Kg/Week) : " + MildWeightLossCalories + "Calories Per Day\nRequired Calorie To Weight Loss (0.5Kg/Week) : " + WeightLossCalories + "Calories Per Day\nRequired Calorie To Extreme Weight Loss (1Kg/Week) : " + ExtremeWeightLossCalories + "Calories Per Day");
    }
    JOptionPane.showMessageDialog(null, "Stay Hydrated , Hit Gym , All The Best\nThank You..");
} //DIET PLAN MANAGEMENT CODE ENDS HERE

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */

    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(DietPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(DietPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(DietPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(DietPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new DietPlan().setVisible(true);
    }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup activity;
    private javax.swing.JTextField age;
    private javax.swing.JButton back;
    private javax.swing.JButton check;
    private javax.swing.JTextField choice;
    private javax.swing.JButton exit;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables

}
